const v2Employees = [
    { firstName: "Alice", lastName: "Johnson", email: "alice.johnson@example.com", employeeID: 8 },
    { firstName: "Bob", lastName: "Smith", email: "bob.smith@example.com", employeeID: 15 },
    { firstName: "Charlie", lastName: "Williams", email: "charlie.williams@example.com", employeeID: 4 },
    { firstName: "Diana", lastName: "Brown", email: "diana.brown@example.com", employeeID: 12 },
    { firstName: "Ella", lastName: "Jones", email: "ella.jones@example.com", employeeID: 20 },
    { firstName: "Frank", lastName: "Taylor", email: "frank.taylor@example.com", employeeID: 11 },
    { firstName: "Grace", lastName: "Miller", email: "grace.miller@example.com", employeeID: 5 },
    { firstName: "Henry", lastName: "Anderson", email: "henry.anderson@example.com", employeeID: 3 },
    { firstName: "Isabella", lastName: "Thomas", email: "isabella.thomas@example.com", employeeID: 14 },
    { firstName: "Jack", lastName: "Hall", email: "jack.hall@example.com", employeeID: 17 },
    { firstName: "Kate", lastName: "Wilson", email: "kate.wilson@example.com", employeeID: 1 },
    { firstName: "Luke", lastName: "Clark", email: "luke.clark@example.com", employeeID: 6 },
    { firstName: "Mia", lastName: "Lewis", email: "mia.lewis@example.com", employeeID: 19 },
    { firstName: "Noah", lastName: "Young", email: "noah.young@example.com", employeeID: 9 },
    { firstName: "Olivia", lastName: "Walker", email: "olivia.walker@example.com", employeeID: 18 },
    { firstName: "Peter", lastName: "Harris", email: "peter.harris@example.com", employeeID: 7 },
    { firstName: "Quinn", lastName: "Martin", email: "quinn.martin@example.com", employeeID: 16 },
    { firstName: "Ryan", lastName: "Thompson", email: "ryan.thompson@example.com", employeeID: 10 },
    { firstName: "Sophie", lastName: "Garcia", email: "sophie.garcia@example.com", employeeID: 2 },
    { firstName: "Thomas", lastName: "Davis", email: "thomas.davis@example.com", employeeID: 13 }
  ];
  const v3Employees = [
    { firstName: "John", lastName: "Doe", email: "john.doe@example.com", employeeID: 1, isActive: true },
    { firstName: "Jane", lastName: "Smith", email: "jane.smith@example.com", employeeID: 2, isActive: false },
    { firstName: "Michael", lastName: "Johnson", email: "michael.johnson@example.com", employeeID: 3, isActive: true },
    { firstName: "Emily", lastName: "Williams", email: "emily.williams@example.com", employeeID: 4, isActive: true },
    { firstName: "Daniel", lastName: "Brown", email: "daniel.brown@example.com", employeeID: 5, isActive: false },
    { firstName: "Olivia", lastName: "Jones", email: "olivia.jones@example.com", employeeID: 6, isActive: true },
    { firstName: "David", lastName: "Taylor", email: "david.taylor@example.com", employeeID: 7, isActive: false },
    { firstName: "Sophia", lastName: "Miller", email: "sophia.miller@example.com", employeeID: 8, isActive: true },
    { firstName: "James", lastName: "Anderson", email: "james.anderson@example.com", employeeID: 9, isActive: true },
    { firstName: "Ava", lastName: "Thomas", email: "ava.thomas@example.com", employeeID: 10, isActive: false },
    { firstName: "Matthew", lastName: "Hall", email: "matthew.hall@example.com", employeeID: 11, isActive: true },
    { firstName: "Isabella", lastName: "Wilson", email: "isabella.wilson@example.com", employeeID: 12, isActive: true },
    { firstName: "Joseph", lastName: "Clark", email: "joseph.clark@example.com", employeeID: 13, isActive: false },
    { firstName: "Emma", lastName: "Lewis", email: "emma.lewis@example.com", employeeID: 14, isActive: true },
    { firstName: "Andrew", lastName: "Young", email: "andrew.young@example.com", employeeID: 15, isActive: true },
    { firstName: "Mia", lastName: "Walker", email: "mia.walker@example.com", employeeID: 16, isActive: false },
    { firstName: "Benjamin", lastName: "Harris", email: "benjamin.harris@example.com", employeeID: 17, isActive: true },
    { firstName: "Ella", lastName: "Martin", email: "ella.martin@example.com", employeeID: 18, isActive: true },
    { firstName: "William", lastName: "Thompson", email: "william.thompson@example.com", employeeID: 19, isActive: false },
    { firstName: "Sofia", lastName: "Garcia", email: "sofia.garcia@example.com", employeeID: 20, isActive: true }
  ];